export const SIDE_QUESTS = [
  { id: "cellar-vermin", giverNpcId: "market", unlockQuestStep: 1, objective: { kind: "combat", targetKey: "rat", target: 3 }, reward: { gold: 90, xpSkill: "defense", xp: 70, itemId: "healing-potion", quantity: 1 } },
  { id: "quarry-ledger", giverNpcId: "smith", unlockQuestStep: 5, objective: { kind: "gather", targetKey: "ore", target: 5 }, reward: { gold: 170, xpSkill: "mining", xp: 180, itemId: "iron-ore", quantity: 3 } },
  { id: "moonfen-remedy", giverNpcId: "ranger", unlockQuestStep: 16, objective: { kind: "gather", targetKey: "fish", target: 4 }, reward: { gold: 260, xpSkill: "fishing", xp: 240, itemId: "healing-potion", quantity: 2 } },
  { id: "catacomb-vigil", giverNpcId: "ranger", unlockQuestStep: 24, objective: { kind: "combat", targetKey: "skeleton", target: 4 }, reward: { gold: 420, xpSkill: "defense", xp: 360, itemId: "sunstone-shard", quantity: 2 } },
];
export function normalizeSideQuestProgress(value) { if (!value || typeof value !== "object" || Array.isArray(value)) return {}; return Object.fromEntries(SIDE_QUESTS.flatMap((quest) => { const state = value[quest.id]; if (!state || !["active", "ready", "claimed"].includes(String(state.status))) return []; const progress = Math.max(0, Math.min(quest.objective.target, Math.floor(Number(state.progress) || 0))); const status = state.status === "claimed" ? "claimed" : progress >= quest.objective.target ? "ready" : "active"; return [[quest.id, { status, progress }]]; })); }
export function advanceSideQuests(progress, kind, targetKey) { const next = normalizeSideQuestProgress(progress); for (const quest of SIDE_QUESTS) { const state = next[quest.id]; if (!state || state.status !== "active" || quest.objective.kind !== kind || quest.objective.targetKey !== targetKey) continue; const amount = Math.min(quest.objective.target, state.progress + 1); next[quest.id] = { status: amount >= quest.objective.target ? "ready" : "active", progress: amount }; } return next; }
export function sideQuestById(id) { return SIDE_QUESTS.find((quest) => quest.id === id); }
