export const SIDE_QUESTS = [
  { id: "cellar-vermin", giverNpcId: "market", unlockQuestStep: 1, objective: { kind: "combat", targetKey: "rat", target: 3 }, reward: { gold: 90, xpSkill: "defense", xp: 70, itemId: "healing-potion", quantity: 1 } },
  { id: "quarry-ledger", giverNpcId: "smith", unlockQuestStep: 5, objective: { kind: "gather", targetKey: "ore", target: 5 }, reward: { gold: 170, xpSkill: "mining", xp: 180, itemId: "iron-ore", quantity: 3 } },
  { id: "moonfen-remedy", giverNpcId: "ranger", unlockQuestStep: 16, objective: { kind: "gather", targetKey: "fish", target: 4 }, reward: { gold: 260, xpSkill: "fishing", xp: 240, itemId: "healing-potion", quantity: 2 } },
  { id: "heartwood-oath", giverNpcId: "ranger", unlockQuestStep: 18, objective: { kind: "combat", targetKey: "briar-treant", target: 1 }, reward: { gold: 480, xpSkill: "defense", xp: 360, itemId: "briarhide-cloak", quantity: 1 } },
  { id: "catacomb-vigil", giverNpcId: "ranger", unlockQuestStep: 24, objective: { kind: "combat", targetKey: "skeleton", target: 4 }, reward: { gold: 420, xpSkill: "defense", xp: 360, itemId: "sunstone-shard", quantity: 2 } },
  { id: "ember-forge", giverNpcId: "smith", unlockQuestStep: 29, objective: { kind: "gather", targetKey: "ember-ore", target: 3 }, reward: { gold: 600, xpSkill: "mining", xp: 520, itemId: "sunstone-pick", quantity: 1 } },
  { id: "lantern-stones", giverNpcId: "fen-cartographer", unlockQuestStep: 30, objective: { kind: "gather", targetKey: "moonfen-ore", target: 3 }, reward: { gold: 460, xpSkill: "mining", xp: 440, itemId: "healing-potion", quantity: 2 } },
  { id: "wraithlight-patrol", giverNpcId: "fen-cartographer", unlockQuestStep: 30, objective: { kind: "combat", targetKey: "moonfen-wraith-1", target: 1 }, reward: { gold: 680, xpSkill: "defense", xp: 560, itemId: "sunstone-shard", quantity: 2 } },
  { id: "caldera-supplies", giverNpcId: "ember-forgekeeper", unlockQuestStep: 35, objective: { kind: "gather", targetKey: "ember-ore", target: 4 }, reward: { gold: 720, xpSkill: "mining", xp: 640, itemId: "healing-potion", quantity: 3 } },
  { id: "cinderwatch", giverNpcId: "ember-forgekeeper", unlockQuestStep: 35, objective: { kind: "combat", targetKey: "emberfall-cinder-guard-1", target: 1 }, reward: { gold: 940, xpSkill: "defense", xp: 760, itemId: "sunstone-shard", quantity: 3 } },
  { id: "frostglass-relay", giverNpcId: "frostkeeper", unlockQuestStep: 40, objective: { kind: "gather", targetKey: "frost-ore", target: 3 }, reward: { gold: 560, xpSkill: "mining", xp: 620, itemId: "healing-potion", quantity: 3 } },
  { id: "last-beacon", giverNpcId: "frostkeeper", unlockQuestStep: 40, objective: { kind: "combat", targetKey: "frostmere-warden", target: 1 }, reward: { gold: 900, xpSkill: "defense", xp: 700, itemId: "moonweave-mantle", quantity: 1 } },
  { id: "oasis-sounding", giverNpcId: "sunscar-scholar", unlockQuestStep: 45, objective: { kind: "gather", targetKey: "sunscar-fish", target: 3 }, reward: { gold: 720, xpSkill: "fishing", xp: 760, itemId: "healing-potion", quantity: 3 } },
  { id: "solar-seal", giverNpcId: "sunscar-scholar", unlockQuestStep: 45, objective: { kind: "combat", targetKey: "sunscar-tomb-king", target: 1 }, reward: { gold: 1250, xpSkill: "defense", xp: 980, itemId: "sunforged-mail", quantity: 1 } },
];
export function normalizeSideQuestProgress(value) { if (!value || typeof value !== "object" || Array.isArray(value)) return {}; return Object.fromEntries(SIDE_QUESTS.flatMap((quest) => { const state = value[quest.id]; if (!state || !["active", "ready", "claimed"].includes(String(state.status))) return []; const progress = Math.max(0, Math.min(quest.objective.target, Math.floor(Number(state.progress) || 0))); const status = state.status === "claimed" ? "claimed" : progress >= quest.objective.target ? "ready" : "active"; return [[quest.id, { status, progress }]]; })); }
export function advanceSideQuests(progress, kind, targetKey, targetId = "") { const next = normalizeSideQuestProgress(progress); for (const quest of SIDE_QUESTS) { const state = next[quest.id]; const matchesTarget = quest.objective.targetKey === targetKey || quest.objective.targetKey === targetId || (quest.objective.targetKey === "ember-ore" && targetId.startsWith("emberfall-ore-")) || (quest.objective.targetKey === "moonfen-ore" && targetId.startsWith("moonfen-ore-")) || (quest.objective.targetKey === "frost-ore" && targetId.startsWith("frostmere-ore-")) || (quest.objective.targetKey === "sunscar-fish" && targetId.startsWith("sunscar-fish-")) || (quest.objective.targetKey === "frostmere-warden" && targetId === "frostmere-lighthouse-warden"); if (!state || state.status !== "active" || quest.objective.kind !== kind || !matchesTarget) continue; const amount = Math.min(quest.objective.target, state.progress + 1); next[quest.id] = { status: amount >= quest.objective.target ? "ready" : "active", progress: amount }; } return next; }
export function sideQuestById(id) { return SIDE_QUESTS.find((quest) => quest.id === id); }
